const GROUP_TYPE_DISTRIBUTION = "TYPE_DISTRIBUTION"
const GROUP_TYPE_SECURITY = "TYPE_SECURITY"
const GROUP_TYPE_SYSTEM = "TYPE_SYSTEM" // Not selectable
const GROUP_SCOPE_GLOBAL = "SCOPE_GLOBAL"
const GROUP_SCOPE_DOMAIN_LOCAL = "SCOPE_DOMAIN_LOCAL"
const GROUP_SCOPE_UNIVERSAL = "SCOPE_UNIVERSAL"

const GROUP_SCOPE_DEFAULT = GROUP_SCOPE_DOMAIN_LOCAL
const GROUP_TYPE_DEFAULT = GROUP_TYPE_SECURITY

const LDAPGroupTypes = {
	GROUP_TYPE_DISTRIBUTION: GROUP_TYPE_DISTRIBUTION,
	GROUP_TYPE_SECURITY: GROUP_TYPE_SECURITY,
}
const LDAPGroupScopes = {
	GROUP_SCOPE_GLOBAL: GROUP_SCOPE_GLOBAL,
	GROUP_SCOPE_DOMAIN_LOCAL: GROUP_SCOPE_DOMAIN_LOCAL,
	GROUP_SCOPE_UNIVERSAL: GROUP_SCOPE_UNIVERSAL,
}

export {
	GROUP_SCOPE_DEFAULT,
	GROUP_TYPE_DEFAULT,
	GROUP_TYPE_DISTRIBUTION,
	GROUP_TYPE_SECURITY,
	GROUP_TYPE_SYSTEM,
	GROUP_SCOPE_GLOBAL,
	GROUP_SCOPE_DOMAIN_LOCAL,
	GROUP_SCOPE_UNIVERSAL,
	LDAPGroupTypes,
	LDAPGroupScopes,
}